version: '3.8'

services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=user
      - MYSQL_PASSWORD=passw0rd
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
    # networks:
    #   - app-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    environment:
      - SERVER_PORT=8080
      - LOG_LEVEL=ERROR
      - HTTP_TIMEOUTSEC=10
      - DATABASE_MYSQL_DATABASE=mydatabase
      - DATABASE_MYSQL_USER=user
      - DATABASE_MYSQL_PASSWORD=passw0rd
      - DATABASE_MYSQL_HOST=mysql
      - DATABASE_MYSQL_PORT=3306
      - CORS_ALLOW_ALLORIGINS=true
      - CORS_ALLOW_CREDENTIALS=false
      - CORS_ALLOW_METHODS=GET,POST,PUT,PATCH,DELETE,HEAD,OPTIONS
      - CORS_ALLOW_HEADERS=Origin,Content-Length,Content-Type,Authorization
      - CORS_MAXAGE=43200
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    # networks:
    #   - app-network

# networks:
#   app-network:
#     driver: bridge

volumes:
  mysql-data:
